# absolute path to lp yaml file
lightning_pose_config: /teamspace/studios/this_studio/keypoint-pseudo-labeler/configs/config_mirror-mouse.yaml
  
# pose estimation data type
data_type: lp

# initial ensemble seeds
init_ensemble_seeds:
  - 0
  - 1
  # - 2
  # - 3
  # - 4

video_directories:
  # - /teamspace/studios/this_studio/data/mirror-mouse/videos_test
  # - /teamspace/studios/this_studio/data/mirror-mouse/videos_test_new
  - videos_test
  - videos_test_new

# number of pseudo-labels to select for next round of training
n_pseudo_labels: 1000

# pseudo-labeler algorithm (eks, hand, eventually other baselines)
pseudo_labeler: eks

# we pseudo-label all frames in all videos - how to select the final frames?
selection_strategy: random

# size of final ensemble (>1 means we can compare ensemble variance across both rounds)
final_ensemble_seeds: 5

# datasetname:

# 
val_check_interval: 50
train_check_interval: 10