# absolute path to lp yaml file
lightning_pose_config:
  data:
    data_dir: null
  training:
    rng_seed_data_pt: null
    max_steps: 30000
    min_steps: 10000
    unfreeze_step: 300

# pose estimation data type
data_type: lp

# initial ensemble seeds
init_ensemble_seeds:
  - 0
  - 1
  - 2
  - 3
  - 4

video_directories:
  - videos
  - videos_new

# EKS smoothing parameter optimization frames

eks_s_frames: [(,)]

# number of pseudo-labels to select for next round of training
n_pseudo_labels: 1000

# pseudo-labeler algorithm (eks, hand, eventually other baselines)
pseudo_labeler: eks

# we pseudo-label all frames in all videos - how to select the final frames?
selection_strategy: random

# size of final ensemble (>1 means we can compare ensemble variance across both rounds)
final_ensemble_seeds: 5

config_mirror-mouse: /path/to/mirror-mouse-config.yaml
