# absolute path to lp yaml file
lightning_pose_config: /teamspace/studios/this_studio/keypoint-pseudo-labeler/configs/config_mirror-mouse.yaml
  
# pose estimation data type
data_type: lp

# Pipeline seed for initial data split
pipeline_seeds: 0

# initial ensemble seeds
ensemble_seeds:
  - 0
  - 1
  # - 2
  # - 3
  # - 4

video_directories:
  - videos_test
  - videos_test_new
  # - videos
  # - videos_new
# number of pseudo-labels to select for next round of training
n_pseudo_labels: 1000

# pseudo-labeler algorithm (eks, hand, eventually other baselines)
pseudo_labeler: eks
# options: eks, ensemble_mean

# we pseudo-label all frames in all videos - how to select the final frames?
selection_strategy: random

# datasetname:

# training parameters
min_steps: 100
max_steps: 100
milestone_steps: [20, 40, 60]
val_check_interval: 50
train_check_interval: 10

# min_steps: 5000
# max_steps: 5000
# milestone_steps: [2000, 3000 , 4000]
# val_check_interval: 100
# train_check_interval: 10

# min_steps: 200
# max_steps: 200
# milestone_steps: [2, 3 , 5]
# val_check_interval: 2
# train_check_interval: 2