# absolute path to lp yaml file
lightning_pose_config: /teamspace/studios/this_studio/keypoint-pseudo-labeler/configs/config_mirror-mouse.yaml
  
# pose estimation data type
data_type: lp

# initial ensemble seeds
ensemble_seeds:
  - 0
  - 1
  # - 2
  # - 3
  # - 4

video_directories:
  - videos_test
  - videos_test_new

# number of pseudo-labels to select for next round of training
n_pseudo_labels: 1000

# pseudo-labeler algorithm (eks, hand, eventually other baselines)
pseudo_labeler: eks
# options: eks, ensemble_mean

# we pseudo-label all frames in all videos - how to select the final frames?
selection_strategy: random

# size of final ensemble (>1 means we can compare ensemble variance across both rounds)
final_ensemble_seeds: 5

# datasetname:

# training parameters
# min_steps: 300
# max_steps: 300
# milestone_steps: [100, 150, 200]
# val_check_interval: 50
# train_check_interval: 10

min_steps: 100
max_steps: 100
milestone_steps: [30, 50, 70]
val_check_interval: 15
train_check_interval: 4